global using FluentValidation;
global using Mapster;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using SurveyBasket.Web.Contracts.Requests;
global using SurveyBasket.Web.Contracts.Responces;
global using SurveyBasket.Web.Entities;
global using SurveyBasket.Web.Services;
